[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
preDeployCommand = ["npm run db:prepare"]
sleepApplication = false
useLegacyStacker = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10