source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
gem "rack-cors"
gem "jwt"
gem "bcrypt"
gem 'image_processing', '~> 1.14'
gem "jbuilder"
gem 'decent_exposure', '~> 3.0'
gem 'dotenv'
gem 'faraday'

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false

  gem 'rspec-rails', '~> 8.0.0'
  gem 'simplecov', require: false
  gem 'shoulda-matchers', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rails-controller-testing'
  gem 'bullet'
  gem 'vcr'
  gem 'webmock'

  gem "pry", "~> 0.15.0"
  gem "pry-rails"
end