databases:
  - name: postgres
    ipAllowList: []
    databaseName: jira_clone_6x8s
    user: jira_clone_6x8s_user

services:
  - type: web
    name: jira-clone-backend
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
